#   Ensure the posgresql gem is defined in your Gemfile
#   gem 'pg'

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/que-hacer.sqlite3

test:
  <<: *default
  #url: "postgresql://postgres:postgres@localhost:5432/test_todo"
  database: db/que-hacer-test.sqlite3

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>